[package]
name = "nic-roaming"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "nicr"

[dependencies]
net-sys = { path = "../net-sys", features = ["libc"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
